coverage:
  status:
    default_rules:
      if_ci_failed: success
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        flags:
          - Cpp
          - ReactJS
comment:
    after_n_builds: 2
