codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      cpp:
        informational: true
        flags:
          - Cpp

      react:
        informational: true
        flags:
          - ReactJS
    patch:
      default:
        informational: true

comment:
  after_n_builds: 2

