name: cpp-tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"
  workflow_dispatch:

env:
  SOURCE_DIR: ./Sources/backend-cpp
  BUILD_DIR: ./Sources/backend-cpp/build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install Ninja
        run: choco install ninja -y
        shell: powershell

      - name: CMake
        run: cmake -G Ninja -S ${{env.SOURCE_DIR}} -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}}

      - name: Setup OpenCppCoverage and add to PATH
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Run C++ Unit Tests and Generate Coverage Report
        id: generate_test_report
        shell: cmd
        run: |
          OpenCppCoverage.exe ^
            --quiet ^
            --sources Sources\backend-cpp ^
            --excluded_sources Vendor ^
            --excluded_sources Windows ^
            --excluded_sources Tools ^
            --export_type cobertura:StreamdeckDcsInterfaceCov.xml ^
            --cover_children ^
            -- ctest --test-dir ./${{env.BUILD_DIR}} --output-on-failure

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./StreamdeckDcsInterfaceCov.xml
          flags: Cpp
          disable_search: true

